length = int(input("请输入字符串长度:"))
print('=='.center(length-2, '='))
print('Item'+' '.center(length-11, ' ')+'Price')
print('--'.center(length-2, '-'))
print('Apples'+' '.center(length-12, ' ')+'0.40')
print('Pears'+' '.center(length-11, ' ')+'0.50')
print('Cantaloupes'+' '.center(length-17, ' ')+'1.92')
print('Dried Apricots (16 oz.)'+' '.center(length-29, ' ')+'8.00')
print('Prunes (4 1bs.)'+' '.center(length-22, ' ')+'12.00')
print('=='.center(length-2, '='))
